// Buenas prácticas: Barrel export para componentes UI
export { default as Icon } from './Icon.svelte';
export { default as Button } from './Button.svelte';
export { default as Card } from './Card.svelte';
export { default as Section } from './Section.svelte';
export { default as ContactLink } from './ContactLink.svelte';
export { default as Badge } from './Badge.svelte';
export { default as Avatar } from './Avatar.svelte';
export { default as AnimatedSection } from './AnimatedSection.svelte';
export { default as ImagePlaceholder } from './ImagePlaceholder.svelte';
export { default as Modal } from './Modal.svelte';
